name: Production Deployment

on:
  push:
    branches: [ production ]

jobs:
  build:
    name: Deploy
    runs-on: production
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Executing remote  command
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - name: Add .env 
    - run: echo "${{secrets.PROD_ENV}}" > .env
    - run: npm i
    - run: npm run build --if-present
    - run: npm run start:prod
   
